# ancCond.R
# Revised implementation of the ancestral condition test
#
# Core changes in this version:
# 1) The empirical ancestral condition is evaluated at the estimated point of each
#    discrete transition along a branch, not just at nodes.
# 2) Forward and backward transitions are tracked separately.
# 3) The null is generated by simulating binary traits under the fitted Mk model
#    (Q matrix + root probabilities), accepting only simulations with approximately
#    matching tip frequencies and transition counts.
# 4) Optional pruning of the derived state is only used when the user explicitly
#    requests "drop_derived".
# 5) Binary states can be supplied as intelligible labels such as
#    c("diurnal", "nocturnal") rather than 0/1.

ancCondTest <- function(tree,
                        cont_trait,
                        disc_trait,
                        state_order = NULL,
                        derived_state = NULL,
                        drop_derived = FALSE,
                        model = "ARD",
                        nsim_empirical_maps = 100,
                        nsim_null_traits = 1000,
                        nsim_null_maps = 100,
                        acceptance_threshold = NULL,
                        transition_tolerance = 0.25,
                        tip_tolerance = 0.10,
                        max_null_attempts = 50000,
                        pi = "fitzjohn",
                        root_p = NULL,
                        seed = NULL,
                        verbose = TRUE) {

  if (!requireNamespace("ape", quietly = TRUE)) stop("Package 'ape' is required.")
  if (!requireNamespace("phytools", quietly = TRUE)) stop("Package 'phytools' is required.")

  if (!is.null(seed)) set.seed(seed)

  if (!is.null(acceptance_threshold)) {
    transition_tolerance <- acceptance_threshold
    tip_tolerance <- acceptance_threshold
  }

  tree <- ape::reorder.phylo(tree, order = "cladewise")

  # ---------- helpers ----------
  .message <- function(...) if (isTRUE(verbose)) message(...)

  .named_numeric <- function(x, nm) {
    x <- as.numeric(x)
    names(x) <- nm
    x
  }

  .prep_named_vector <- function(x, tip_names, what) {
    if (is.null(names(x))) stop(sprintf("%s must be a named vector with names matching tree$tip.label.", what))
    x <- x[tip_names]
    if (any(is.na(x))) stop(sprintf("%s is missing values for one or more taxa in tree$tip.label.", what))
    x
  }

  .rescale_map_to_fractions <- function(map_vec, edge_length) {
    if (length(map_vec) == 0) return(numeric(0))
    if (edge_length <= 0) return(rep(0, length(map_vec)))
    as.numeric(map_vec) / edge_length
  }

  .count_transitions_from_simmap <- function(simmap_obj, states) {
    out <- stats::setNames(rep(0, length(states) * length(states)), as.vector(outer(states, states, paste, sep = "->")))
    for (i in seq_len(nrow(simmap_obj$edge))) {
      seg_states <- names(simmap_obj$maps[[i]])
      if (length(seg_states) > 1) {
        for (j in seq_len(length(seg_states) - 1)) {
          key <- paste0(seg_states[j], "->", seg_states[j + 1])
          out[key] <- out[key] + 1
        }
      }
    }
    out
  }

  .mean_transition_values_from_map <- function(simmap_obj, node_values, tip_values, states) {
    # For each transition along each edge, estimate the continuous trait value at the
    # exact transition point by linear interpolation between parent and child values.
    vals <- stats::setNames(vector("list", length(states) * length(states)),
                            as.vector(outer(states, states, paste, sep = "->")))

    for (i in seq_len(nrow(simmap_obj$edge))) {
      parent <- simmap_obj$edge[i, 1]
      child  <- simmap_obj$edge[i, 2]
      edge_length <- simmap_obj$edge.length[i]
      map_vec <- simmap_obj$maps[[i]]
      seg_states <- names(map_vec)

      if (length(seg_states) <= 1) next

      parent_val <- if (parent <= Ntip(tree)) tip_values[parent] else node_values[as.character(parent)]
      child_val  <- if (child  <= Ntip(tree)) tip_values[child]  else node_values[as.character(child)]

      frac_lengths <- .rescale_map_to_fractions(map_vec, edge_length)
      cum_frac <- cumsum(frac_lengths)

      # transitions occur at the end of segments 1:(k-1)
      for (j in seq_len(length(seg_states) - 1)) {
        trans_frac <- cum_frac[j]
        trans_val <- parent_val + trans_frac * (child_val - parent_val)
        key <- paste0(seg_states[j], "->", seg_states[j + 1])
        vals[[key]] <- c(vals[[key]], trans_val)
      }
    }

    means <- vapply(vals, function(x) if (length(x) == 0) NA_real_ else mean(x), numeric(1))
    counts <- vapply(vals, length, integer(1))
    list(values = vals, means = means, counts = counts)
  }

  .estimate_continuous_states <- function(tree_use, cont_use) {
    fit <- phytools::anc.ML(tree_use, cont_use)
    node_ids <- (Ntip(tree_use) + 1):(Ntip(tree_use) + tree_use$Nnode)
    node_vals <- fit$ace
    names(node_vals) <- as.character(node_ids)
    tip_vals <- cont_use[tree_use$tip.label]
    list(node_values = node_vals, tip_values = tip_vals, fit = fit)
  }

  .fit_discrete_model <- function(tree, disc_factor, model = "ARD", pi = "fitzjohn", root_p = NULL) {
    states <- levels(disc_factor)
    if (!is.null(root_p)) {
      root_p <- root_p[states]
      if (any(is.na(root_p))) stop("root_p must be named with the discrete state labels.")
      root_p <- root_p / sum(root_p)
      fit <- phytools::fitMk(tree, disc_factor, model = model, pi = root_p)
      pi_used <- root_p
    } else {
      fit <- phytools::fitMk(tree, disc_factor, model = model, pi = pi)
      pi_used <- fit$pi
      if (is.null(pi_used)) stop("Could not recover root probabilities from fitMk().")
      pi_used <- pi_used[states]
      pi_used <- pi_used / sum(pi_used)
    }
    list(fit = fit, Q = fit$rates, pi = pi_used)
  }

  .make_Q_matrix <- function(fit_obj, states) {
    Q <- as.matrix(fit_obj$fit$rates)
    if (!all(rownames(Q) == states) || !all(colnames(Q) == states)) {
      Q <- Q[states, states, drop = FALSE]
    }
    Q
  }

  .get_empirical_transition_targets <- function(tree, disc_factor, Q, pi_vec, states, n_maps) {
    maps <- phytools::make.simmap(tree, disc_factor, model = Q, pi = pi_vec, nsim = n_maps, message = FALSE)
    if (inherits(maps, "phylo")) maps <- list(maps)
    counts_mat <- do.call(rbind, lapply(maps, .count_transitions_from_simmap, states = states))
    mean_counts <- colMeans(counts_mat)
    list(maps = maps, mean_transition_counts = mean_counts, transition_count_matrix = counts_mat)
  }

  .tip_counts <- function(x, states) {
    tab <- table(factor(as.character(x), levels = states))
    out <- as.numeric(tab)
    names(out) <- states
    out
  }

  .within_tolerance <- function(sim_counts, emp_counts, tol) {
    all(abs(sim_counts - emp_counts) <= pmax(1, emp_counts * tol))
  }

  .simulate_one_discrete_history <- function(tree, Q, pi_vec, states) {
    sim_hist <- phytools::sim.history(tree, Q = Q, anc = sample(states, 1, prob = pi_vec), message = FALSE)
    tip_states <- sim_hist$states[tree$tip.label]
    list(simmap = sim_hist, tip_states = factor(tip_states, levels = states))
  }

  .empirical_p <- function(obs, null) {
    null <- null[is.finite(null)]
    if (!is.finite(obs) || length(null) == 0) return(NA_real_)
    more_extreme <- sum(abs(null - mean(null)) >= abs(obs - mean(null)))
    (more_extreme + 1) / (length(null) + 1)
  }

  # ---------- input prep ----------
  cont_trait <- .prep_named_vector(cont_trait, tree$tip.label, "cont_trait")
  disc_trait <- .prep_named_vector(disc_trait, tree$tip.label, "disc_trait")

  disc_trait <- as.character(disc_trait)
  if (length(unique(stats::na.omit(disc_trait))) != 2) stop("disc_trait must contain exactly two states.")

  if (is.null(state_order)) {
    states <- sort(unique(disc_trait))
  } else {
    states <- as.character(state_order)
    if (length(states) != 2) stop("state_order must contain exactly two state labels.")
    if (!setequal(states, unique(disc_trait))) stop("state_order must match the two observed states in disc_trait.")
  }

  disc_factor <- factor(disc_trait, levels = states)
  transition_keys <- c(paste0(states[1], "->", states[2]), paste0(states[2], "->", states[1]))

  if (drop_derived) {
    if (is.null(derived_state)) stop("When drop_derived = TRUE, you must provide derived_state.")
    if (!(derived_state %in% states)) stop("derived_state must be one of the two discrete-state labels.")
    keep <- names(disc_factor)[disc_factor != derived_state]
    tree_cont <- ape::drop.tip(tree, setdiff(tree$tip.label, keep))
    cont_for_fit <- cont_trait[tree_cont$tip.label]
    cont_fit <- .estimate_continuous_states(tree_cont, cont_for_fit)

    # project node states back onto original tree where possible, then estimate all-node values
    # on the original tree using all tips as a practical fallback.
    .message("drop_derived = TRUE: continuous ancestral states were first estimated after pruning the derived state.")
  }

  cont_fit_full <- .estimate_continuous_states(tree, cont_trait)
  node_values <- cont_fit_full$node_values
  tip_values  <- cont_fit_full$tip_values

  disc_fit <- .fit_discrete_model(tree, disc_factor, model = model, pi = pi, root_p = root_p)
  Q <- .make_Q_matrix(disc_fit, states = states)
  pi_vec <- disc_fit$pi

  # ---------- empirical statistic ----------
  .message("Estimating empirical stochastic maps...")
  empirical_maps <- phytools::make.simmap(tree, disc_factor, model = Q, pi = pi_vec,
                                          nsim = nsim_empirical_maps, message = FALSE)
  if (inherits(empirical_maps, "phylo")) empirical_maps <- list(empirical_maps)

  empirical_transition_values <- lapply(empirical_maps, .mean_transition_values_from_map,
                                        node_values = node_values,
                                        tip_values = tip_values,
                                        states = states)

  empirical_means_matrix <- do.call(rbind, lapply(empirical_transition_values, function(x) x$means[transition_keys]))
  empirical_counts_matrix <- do.call(rbind, lapply(empirical_transition_values, function(x) x$counts[transition_keys]))

  empirical_mean_transition_counts <- colMeans(empirical_counts_matrix)
  empirical_tip_counts <- .tip_counts(disc_factor, states)

  observed_means <- colMeans(empirical_means_matrix, na.rm = TRUE)
  names(observed_means) <- transition_keys

  # ---------- null distribution ----------
  .message("Generating accepted null discrete traits...")
  accepted_null <- vector("list", nsim_null_traits)
  accepted <- 0L
  attempts <- 0L

  while (accepted < nsim_null_traits && attempts < max_null_attempts) {
    attempts <- attempts + 1L

    sim_hist <- .simulate_one_discrete_history(tree, Q = Q, pi_vec = pi_vec, states = states)
    sim_tip_counts <- .tip_counts(sim_hist$tip_states, states)
    sim_trans_counts <- .count_transitions_from_simmap(sim_hist$simmap, states = states)[transition_keys]

    ok_tips <- .within_tolerance(sim_tip_counts, empirical_tip_counts, tip_tolerance)
    ok_trans <- .within_tolerance(sim_trans_counts, empirical_mean_transition_counts, transition_tolerance)

    if (ok_tips && ok_trans) {
      accepted <- accepted + 1L
      accepted_null[[accepted]] <- list(simmap = sim_hist$simmap,
                                        tip_states = sim_hist$tip_states,
                                        tip_counts = sim_tip_counts,
                                        transition_counts = sim_trans_counts)
      if (verbose && accepted %% 50 == 0) .message("Accepted ", accepted, " / ", nsim_null_traits, " null traits")
    }
  }

  if (accepted < nsim_null_traits) {
    warning(sprintf("Only accepted %d null traits after %d attempts. Consider loosening tolerances.", accepted, attempts))
    if (accepted > 0) {
      accepted_null <- accepted_null[seq_len(accepted)]
    } else {
      accepted_null <- list()
    }
  }

  rejected <- attempts - length(accepted_null)
  rejection_rate <- if (attempts > 0) rejected / attempts else NA_real_
  acceptance_rate <- if (attempts > 0) length(accepted_null) / attempts else NA_real_

  # For each accepted null trait: run 100 stochastic maps and calculate transition-point means
  .message("Mapping accepted null traits and calculating null ancestral conditions...")
  null_means_list <- vector("list", length(accepted_null))

  for (i in seq_along(accepted_null)) {
    tip_states_i <- accepted_null[[i]]$tip_states
    null_maps_i <- phytools::make.simmap(tree,
                                         x = tip_states_i,
                                         model = Q,
                                         pi = pi_vec,
                                         nsim = nsim_null_maps,
                                         message = FALSE)
    if (inherits(null_maps_i, "phylo")) null_maps_i <- list(null_maps_i)

    vals_i <- lapply(null_maps_i, .mean_transition_values_from_map,
                     node_values = node_values,
                     tip_values = tip_values,
                     states = states)
    means_i <- do.call(rbind, lapply(vals_i, function(x) x$means[transition_keys]))
    null_means_list[[i]] <- colMeans(means_i, na.rm = TRUE)
  }

  null_means_matrix <- do.call(rbind, null_means_list)
  colnames(null_means_matrix) <- transition_keys

  p_values <- stats::setNames(
    vapply(transition_keys,
           function(k) .empirical_p(observed_means[[k]], null_means_matrix[, k]),
           numeric(1)),
    transition_keys
  )

  structure(list(
    call = match.call(),
    states = states,
    transition_labels = transition_keys,
    tree = tree,
    q_matrix = Q,
    root_probabilities = pi_vec,
    empirical_tip_counts = empirical_tip_counts,
    empirical_mean_transition_counts = empirical_mean_transition_counts,
    observed_means = observed_means,
    null_means = null_means_matrix,
    p_values = p_values,
    empirical_map_means = empirical_means_matrix,
    empirical_map_counts = empirical_counts_matrix,
    accepted_null_traits = accepted_null,
    attempts = attempts,
    accepted = length(accepted_null),
    rejected = rejected,
    rejection_rate = rejection_rate,
    acceptance_rate = acceptance_rate,
    settings = list(
      model = model,
      nsim_empirical_maps = nsim_empirical_maps,
      nsim_null_traits = nsim_null_traits,
      nsim_null_maps = nsim_null_maps,
      acceptance_threshold = acceptance_threshold,
      transition_tolerance = transition_tolerance,
      tip_tolerance = tip_tolerance,
      drop_derived = drop_derived,
      derived_state = derived_state,
      pi = pi
    )
  ), class = "ancCondTest")
}

print.ancCondTest <- function(x, ...) {
  cat("Ancestral Condition Test\n")
  cat("States:", paste(x$states, collapse = " / "), "\n")
  cat("Accepted null traits:", x$accepted, "of", x$settings$nsim_null_traits,
      "after", x$attempts, "attempts\n")
  cat("Rejected candidate histories:", x$rejected, sprintf("(%.1f%%)", 100 * x$rejection_rate), "\n\n")

  out <- data.frame(
    transition = x$transition_labels,
    observed_mean = unname(x$observed_means[x$transition_labels]),
    null_mean = unname(colMeans(x$null_means[, x$transition_labels, drop = FALSE], na.rm = TRUE)),
    p_value = unname(x$p_values[x$transition_labels]),
    row.names = NULL
  )
  print(out, row.names = FALSE)
  invisible(x)
}

summary.ancCondTest <- function(object, ...) {
  print(object)
  invisible(object)
}

# -----------------------------------------------------------------------------
# Minimal example
# -----------------------------------------------------------------------------
# library(ape)
# library(phytools)
#
# set.seed(1)
# tr <- pbtree(n = 100)
# cont <- fastBM(tr)
# disc <- sample(c("diurnal", "nocturnal"), Ntip(tr), replace = TRUE)
# names(cont) <- tr$tip.label
# names(disc) <- tr$tip.label
#
# res <- ancCondTest(
#   tree = tr,
#   cont_trait = cont,
#   disc_trait = disc,
#   state_order = c("diurnal", "nocturnal"),
#   derived_state = "nocturnal",
#   drop_derived = FALSE,
#   nsim_empirical_maps = 100,
#   nsim_null_traits = 200,
#   nsim_null_maps = 100,
#   seed = 123
# )
#
# print(res)
